apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    service: ambassador
  name: ambassadors
spec:
  ports:
  - name: ambassador
    port: 80
    targetPort: {{ .Values.ambassador.servicePort }}
  selector:
    service: ambassador
  type: {{ .Values.ambassador.serviceType }}
