apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    service: ambassador-admin
  name: ambassador-admin
spec:
  ports:
  - name: ambassador-admin
    port: 8877
    targetPort: {{ .Values.ambassador.adminServicePort }}
  selector:
    service: ambassador
  type: {{ .Values.ambassador.adminServiceType }}
