apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "kubeflow.fullname" . }}-ambassador"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.ambassador.replicaCount }}
  template:
    metadata:
      labels:
        service: ambassador
    spec:
      containers:
      - env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "true"
        image: {{ .Values.ambassador.image }}
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 30
        name: ambassador
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          limits:
            cpu: {{ .Values.ambassador.limitsCpu }}
            memory: {{ .Values.ambassador.limitsMemory }}
          requests:
            cpu: {{ .Values.ambassador.requestsCpu }}
            memory: {{ .Values.ambassador.requestsMemory }}
      - image: {{ .Values.ambassador.statsdImage }}
        name: statsd
      restartPolicy: Always
      serviceAccountName: ambassador
