# Default values for iperf3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: wadelee/iperf3
imageTag: latest
imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5201

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: iperf3
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: 128Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 200m

nodeSelector: {}

tolerations: []

affinity: {}
