{
 "title": "#workloadName",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aliyunNode",
    "query": "label_values(node_boot_time{job=\"aliyun\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "aliyun", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "#workloadName",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "#PromQL{workloadName=\"#workloadName\",provider=\"aliyun\"}"
    }
   ]
  },
  {
   "title": "#MetricsTestCase",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(#PromQL{workloadName=\"#workloadName\",provider=\"aliyun\",testCase=\"#testCase\"})"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=\"$aliyunNode\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$aliyunNode\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$aliyunNode\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$aliyunNode\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=\"$aliyunNode\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=\"$aliyunNode\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$aliyunNode\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$aliyunNode\"} - node_memory_MemFree{instance=\"$aliyunNode\"} - node_memory_Buffers{instance=\"$aliyunNode\"} - node_memory_Cached{instance=\"$aliyunNode\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$aliyunNode\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{instance=\"$aliyunNode\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{instance=\"$aliyunNode\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=\"$aliyunNode\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=\"$aliyunNode\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}